### PR TITLE
fixed padding/margin for food icons

### PR DESCRIPTION
**Pull request by marq24**
The circle of the food icons was clipped - simple fix

### CODE REVIEW

**Comment by pathmapper** [comment]
Hi @marq24, good find and  thanks for your PR!

The SVGs are created using the `iconset.json` with the [Maki Editor](https://www.mapbox.com/maki-icons/editor/).
So theoretically there's no need to adapt the SVGs manually.
Also there's a need to create new sprites.

The whole workflow is described here: https://github.com/maputnik/osm-liberty#icon-design 

Do you want to take a look?

**Comment by marq24** [comment]
Well - what should I say - when the food icons have been created via the Maki Editor then something went wrong during the creation/export process... but at the end that's not important at all...

The reason why I initially did not provide an updates spriteset was, that not all svgs that are present in the PNG/JSON have been present in your gh-branch... [the png include additional road signs -> which came IMHO from this branch that's not merged yet - https://github.com/kylebarron/osm-liberty/tree/highway-shields]... 

Since I obviously did not wanted to provide "less" then before with my PR I did not included an updated png/json... 

You can cherry-pick if you like (since you might want to give the kudos to kylebarron for providing the icons).

Cheers!

**Comment by pathmapper** [comment]
> when the food icons have been created via the Maki Editor then something went wrong during the creation/export process... but at the end that's not important at all...

The idea is that the SVGs which are part of the iconset are generated _automatically_ using the Maki Editor, so they should not be modified manually. #101 fixes the iconset, so that the circle of the icons isn't cropped anymore and the SVGs could be created automatically.

> the png include additional road signs -> which came IMHO from this branch that's not merged yet 

Thanks for spotting this. The additional road signs are coming from this open PR https://github.com/maputnik/osm-liberty/pull/80, so they shouldn't be part of the sprite before #80 is merged. Looks like they accidently came in with https://github.com/maputnik/osm-liberty/commit/37a781277020e57f77d1a86e7f5b5768439a64fc.

Closing here in favor of #101, thanks again for reporting these issues @marq24 !

**Comment by kylebarron** [comment]
> Looks like they accidently came in with [37a7812](https://github.com/maputnik/osm-liberty/commit/37a781277020e57f77d1a86e7f5b5768439a64fc).

🤦‍♂️ Sorry about that! The dangers of building with a dirty git state

**Comment by pathmapper** [comment]
No worries @kylebarron, I'm glad you started https://github.com/maputnik/osm-liberty/pull/80 :smile:

**Pull request closed without merging**
